#!/bin/bash

PROJECT="slack-status-cli"

python -m pip install pip==21.2.0 pip-tools==6.5.0 --no-cache

if [ ! -d "./$PROJECT.venv" ]; then
    python -m venv ./$PROJECT.venv
fi

source ./$PROJECT.venv/bin/activate

pip-sync ./requirements_dev.txt
